version: "3.9"

services:

  django-origo:
    container_name: django-origo
    build:
      context: ./
      dockerfile: ./.docker/django/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt
    restart: unless-stopped
  
  node-origo:
    container_name: node-origo
    build:
      context: ./
      dockerfile: ./.docker/node/Dockerfile
    volumes: 
      - ./react:/opt/app/
    restart: unless-stopped

  nginx-origo:
    container_name: nginx-origo
    build:
      context: ./.docker/nginx
      args:
        ENABLED_MODULES: brotli headers-more modsecurity
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.docker/nginx/templates:/etc/nginx/templates:ro
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped